### ISSUE TITLE
2021/11/9のデータ更新

### ISSUE THREAD

**Issue by jollyjoester** [codeforinzai/open-data-inzai#6]
保育園情報の更新

> 保育園（公立及び私立）　令和3年11月1日時点

**Comment by ota2000** [comment]
@jollyjoester 本件以外にも多数更新があったためデータ更新のPRを作成しました。
https://github.com/codeforinzai/open-data-inzai/pull/7

**Comment by ota2000** [comment]
2024/07末時点の最新データに更新済み
